### ISSUE TITLE
Support for Commerce product variants

### ISSUE THREAD

**Issue by thisisjamessmith** [putyourlightson/craft-blitz-recommendations#1]
When listing products that have variants, they should be eager loaded. Blitz Recommnedations currently does not pick up this for example:

```
{% set products = craft.products.all() %}

{% for product in products %}
     <h2>{{ product.title }}</h2>
     {% if product.variants %}
         <ul>
            {% for variant in product.variants %}
                 <li>{{ variant.title }}</li>
            {% endfor %}
         </ul>
     {% endif %}
{% endfor %}
```

Should be:

```{% set products = craft.products.with(['variants']).all() %}```

**Comment by bencroker** [comment]
Thanks @thisisjamessmith, marking as a feature request.

**Comment by bencroker** [comment]
I gave this some further thought and decided that adding support for module/plugin specific elements is outside the scope of this plugin.
