### ISSUE TITLE
Utilities > Blitz Recommendations Error

### ISSUE THREAD

**Issue by davidhellmann** [putyourlightson/craft-blitz-recommendations#10]
When I go to this Page: `/admin/utilities/blitz-recommendations` I get this error:

![CleanShot 2022-05-09 at 10 27 33](https://user-images.githubusercontent.com/764292/167370724-4114dc4c-1feb-4af3-911d-6fd382e1684e.png)

Craft Version: Craft CMS 4.0.1
Plugin Version: 2.0.0

**Comment by bencroker** [comment]
Thanks for reporting, fixed in https://github.com/putyourlightson/craft-blitz-recommendations/commit/3ebe41b7bc2bfbaebdc09a10216b6f546afff4ea and released in version 2.0.1.
