### ISSUE TITLE
craft blitz-recommendations/recommendations/clear

### ISSUE THREAD

**Issue by AndrewMac** [putyourlightson/craft-blitz-recommendations#11]
Hi Ben, I clear recommendations as part of my composer update, and it's been working just fine for ages. But this morning, after updating to Blitz 4.1 and Recommendations 2.1, I get the error message below. I ran 'php craft' to check all available commands, and it didn't seem to be listed … did that somehow sort of got lost when you split the package out into Blitz Hints? Or do you think something might be wrong at my end?

On the same sort of topic, by the way, do we still need Recommendations anymore if we're running Bllitz? 

```
> @php craft install/check && php craft blitz-recommendations/recommendations/clear || return 0
Craft is installed.
Unknown command: blitz-recommendations/recommendations/clear
Caused by: Exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "blitz-recommendations/recommendations/clear".'

in /app/vendor/yiisoft/yii2/base/Module.php:561

Stack trace:
#0 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('blitz-recommend...', Array)
#1 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('blitz-recommend...', Array)
#2 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('blitz-recommend...', Array)
#3 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#4 /app/craft(13): yii\base\Application->run()
#5 {main}
/app $ php craft
```

**Comment by bencroker** [comment]
Yes, that got carried over to the new package, so this is the command to use now, sorry about not documenting that change.

```shell
php craft blitz/hints/clear
```

**Comment by AndrewMac** [comment]
Hi Ben, thanks so much but I'm so very sorry. I really should have noticed the new command: it's listed there in plain sight! I'm not sure how I missed it, but I guess I was looking for "recommendations" and just completely overlooked the entry for "blitz/hints". So apologies for taking up your time with a question I should have been able to resolve myself … but thanks so much for your help, too!

**Comment by bencroker** [comment]
That's ok, I also made a mistake in that I said that was moved into the Blitz Hints package, when in fact it was moved over to Blitz. Since the Blitz Recommendations plugin is now only a thin wrapper around Blitz Hints (too much naming, I know!), it has lost the console command (which was never a documented feature to begin with).
