### ISSUE TITLE
Blitz Hints suggesting eager loading on the Cart/Order element in Craft Commerce

### ISSUE THREAD

**Issue by robzor** [putyourlightson/craft-blitz-recommendations#12]
I know this is incredibly edge case but I wanted to let you know:

I have a custom field (the Gift Voucher field from verbbs Gift Voucher plugin) in my Commerce Order field layout. 

Blitz Hints suggest that I eager load this field in every instance/template/partial that I call the `craft.commerce.carts.cart` but if I do this, I find that `.with()` is not supported on the Order (Cart) model and instead gives me a WSOD.

This is the code I tried:

```
{% if cart is not defined %}
    {% set cart = craft.commerce.carts.cart.with(['giftVoucherCodes']) %}
  {% else %}
    {% do eagerLoadElements(cart, [
      'giftVoucherCodes'
    ]) %}
  {% endif %}
```

Adding `.collect()` or otherwise doesn't affect the Blitz hints message, the `{% do eagerLoadElements ... %} bit does for defined carts though.

Craft: 4.3.11
Blitz: 4.4.1
Commerce: 4.2.5.1

So I'm guessing either that hint needs to be removed or I am missing something about using `.with()` in the Order model.

Thanks!

**Comment by bencroker** [comment]
Thanks for the heads-up! Can you show the error stack trace please?

**Comment by robzor** [comment]
```
Calling unknown method: craft\commerce\elements\Order::with()
```

**Comment by bencroker** [comment]
You can only call `.with()` on an element query, whereas you’re calling it on an Order element. See the sample usage in the [docs](https://craftcms.com/docs/commerce/4.x/orders-carts.html#with).

I’m not sure you can eager-load elements when calling `craft.commerce.carts.cart`, you’d have to ask the Commerce team about that.

**Comment by robzor** [comment]
Yeah, I thought as much, that's why I was saying that it's odd that Blitz Hints is giving me this:

![CleanShot 2023-03-09 at 2 30 21](https://user-images.githubusercontent.com/704032/224055903-58c83476-3632-4b7c-b41a-6b861ced4b69.png)

**Comment by bencroker** [comment]
Right, it’s not differentiating between the code that called the lazy-loaded query, just noting that it was called. I could make an exception for cart orders, I’ll make a note to look into it.

**Comment by bencroker** [comment]
This isn’t great but it should satisfy Blitz Hints.

```twig
{% set cart = craft.commerce.carts.cart %}
{% do craft.app.elements.eagerLoadElements(
    className(cart),
    [cart],
    ['giftVoucherCodes']
) %}
```

**Comment by robzor** [comment]
Ahh interesting, I missed that there was a `carts.cart` method. I think I might stick it in so that I get rid of the Hints message!

Thanks for getting back to me Ben, always appreciate it :)
