### ISSUE TITLE
String templates in recommendations

### ISSUE THREAD

**Issue by pixelmachine** [putyourlightson/craft-blitz-recommendations#14]
Not sure if this is peculiar to my setup but I'm working through issues and seem to get a lot of recommendations that I can't seem to clear that look like:

```
Recommendation                | Template
-----------------------------------------------------------------------------------
Eager-load the Modules field. | __string_template__6dcb1d05a481cec054e4fae05b599547
```

The original version of the template has been 'fixed' and all caches have been cleared. Template caching is disabled. Some of them eventually disappear after corresponding issues in the templates are fixed but others just always come back.

**Comment by pixelmachine** [comment]
Forgot to say:
Craft: 3.9.6
Blitz: 3.13.0
Recommendations: 1.3.0

**Comment by bencroker** [comment]
Is there anything in that compiled template that might give you clues? If the issue keeps returning after clearing compiled template caches then it is likely an issue with your templates, but I can’t really help without seeing something more substantial.

**Comment by pixelmachine** [comment]
I have no idea @bencroker how do I find the compiled template?

**Comment by bencroker** [comment]
Well, the template name should tell you that.

**Comment by pixelmachine** [comment]
You would think so! 

I can't find a compiled template with that name but I can find a template that refers to that name (content below). Is that the template? Sorry my searches haven't really turned up much info about how compiled templates work and I have never before had to interact with them.

```php
/* __string_template__6dcb1d05a481cec054e4fae05b599547 */
class __TwigTemplate_19f7030696b2dad9025910faa69e83f3 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        craft\helpers\Template::beginProfile("template", "__string_template__6dcb1d05a481cec054e4fae05b599547");
        // line 1
        echo craft\helpers\Template::attribute($this->env, $this->source, craft\helpers\Template::attribute($this->env, $this->source, ($context["seomatic"] ?? null), "helper", []), "extractTextFromField", [0 => craft\helpers\Template::attribute($this->env, $this->source, ($context["shop"] ?? null), "modules", [])], "method");
        craft\helpers\Template::endProfile("template", "__string_template__6dcb1d05a481cec054e4fae05b599547");
    }

    public function getTemplateName()
    {
        return "__string_template__6dcb1d05a481cec054e4fae05b599547";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  38 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("{{ seomatic.helper.extractTextFromField(shop.modules) }}", "__string_template__6dcb1d05a481cec054e4fae05b599547", "");
    }
}
```

I guess the implication here is that it's related to something SEOmatic is doing though I've cleared it's cache too.

**Comment by bencroker** [comment]
That’s it. Do you know what `modules` refers to in `shop.modules`? If it’s an elements field then that is likely the culprit here.

**Comment by pixelmachine** [comment]
Well the modules field is always a matrix so that is the problem I guess. ~However I don't have a single instance of `shop.modules` in my code or in the SEOmatic settings.~

Found it in my SEOmatic settings.

But either way that's not a problem for you! Thanks for helping me debug this.

**Comment by pixelmachine** [comment]
So, on further investigation, this basically occurs for all instances of SEOmatic using an element field:

<img width="531" alt="Screenshot 2023-12-21 at 10 40 34 AM" src="https://github.com/putyourlightson/craft-blitz-recommendations/assets/1082223/569fac60-5a49-45df-bc6c-0b1e5825a2a3">
<img width="1052" alt="Screenshot 2023-12-21 at 10 42 19 AM" src="https://github.com/putyourlightson/craft-blitz-recommendations/assets/1082223/cf7a387f-ba74-418b-9372-d0f8e304de87">

**Comment by bencroker** [comment]
Right, I'm not sure there's anything you can do about that.

**Comment by pixelmachine** [comment]
Yep agreed.
https://github.com/nystudio107/craft-seomatic/issues/1198
