### ISSUE TITLE
Blitz hints + Empty coalesce

### ISSUE THREAD

**Issue by leowebguy** [putyourlightson/craft-blitz-recommendations#15]
Getting these hints from Blitz, regarding eager loading elements.

```
Eager-load the Img field. | _comps/img.twig:10
Eager-load the SVG field. | _comps/resources.twig:29
```

But since I'm using nystudio107/craft-emptycoalesce, this is what I have in my twig `img: comp.img_.one ??? null`

I believe Blitz want me to convert to `img: comp.img_.one ?? null`

Check if this can be added to the whitelist.

![Screenshot 2024-01-09 at 10 55 34 AM](https://github.com/putyourlightson/craft-blitz-recommendations/assets/8460020/ab0b7607-08f7-45aa-a92f-e1260f7c749a)

**Comment by bencroker** [comment]
It looks like you still may need to eager-load the `img_` field.

**Comment by leowebguy** [comment]
I see the problem now... is actually looking for the `.with(['assetsField'])` property.

But this is actually a component, receiving the properties from a Neo field.

```
{% set props = {
    img: comp.img_.one ??? null,
    class: 'img-fluid ' ~ (comp.class_ ??? null),
    width: comp.width_ ??? 'auto',
    height: comp.height_ ??? 'auto',
} %}
```

No problem, I'll ignore those hints for now.
