### ISSUE TITLE
Include Page URL or template include() stack trace information with each hint

### ISSUE THREAD

**Issue by jrrdnx** [putyourlightson/craft-blitz-recommendations#16]
We use a fairly robust "content block" setup for all of our sites, which results in several levels of included templates. While the current hints include the template:line that are creating the recommendation, it sometimes makes it pretty difficult to track down when that particular template can be included several different ways. It would greatly help to have the page URL that triggered the hint, or even a stack trace of the template `include()`s to help track down the actual occurrence.

<img width="951" alt="Screenshot 2024-03-07 at 14 59 04" src="https://github.com/putyourlightson/craft-blitz-recommendations/assets/4584671/fb582615-1a51-40d5-ba81-a718601f88e8">
<img width="376" alt="Screenshot 2024-03-07 at 14 59 12" src="https://github.com/putyourlightson/craft-blitz-recommendations/assets/4584671/9d87f422-8da3-4575-97f4-3e0d4e931cc4">

**Comment by bencroker** [comment]
Thanks for the suggestion. Added a template stack trace in [2.2.0](https://github.com/putyourlightson/craft-blitz-recommendations/releases/tag/2.2.0).

![screenshot-aQ9JKMZX@2x](https://github.com/putyourlightson/craft-blitz-recommendations/assets/57572400/529cff54-9aed-4a68-9a3b-5e7f1ed792dc)
