### ISSUE TITLE
Eager loading for auto-injected elements

### ISSUE THREAD

**Issue by thisisjamessmith** [putyourlightson/craft-blitz-recommendations#3]
Blitz Recommendations gives recommendations for eager loading things which cannot be natively eager loaded - i.e., those that belong to automatically-injected elements. As far as I'm aware this requires the [Eager Beaver](https://nystudio107.com/docs/eager-beaver/) plugin.

**Comment by bencroker** [comment]
It's not pretty, but it can be done in native Craft too:

```twig
{% do craft.app.elements.eagerLoadElements(className(entry), [entry], ['images']) %}
```

Are you by any chance running Craft 3.5? This plugin has not been updated to fully support Craft 3.5 and may result in false negatives.

**Comment by thisisjamessmith** [comment]
Thanks for that! I never realised it was possible natively. Not running 3.5 yet, no.

**Comment by bencroker** [comment]
Source: https://docs.craftcms.com/api/v3/craft-services-elements.html#method-eagerloadelements

**Comment by bencroker** [comment]
Watch the presentation at https://youtu.be/RGK1JHDxHhY

**Comment by bencroker** [comment]
FYI version 2.1.0 improves the behaviour of hints, see https://putyourlightson.com/articles/ballroom-blitz
