### ISSUE TITLE
Disable recommendations for cp

### ISSUE THREAD

**Issue by martijnvanonz** [putyourlightson/craft-blitz-recommendations#4]
Thank you for the plugin! it's really useful.

### Is your feature request related to a problem? Please describe.
The plugin also shows recommendations for the cp panel and files that are in the vendor folder. This is useful when you are developing a plugin or module, but when working on the frontend it makes finding the right recommendations a bit hard.

### Describe the solution you would like
Maybe its an idea to have a setting panel where you can choose if you want recommendations for the cp panel.

### Describe alternatives you have considered
Clear the recommendations and then reload the frontend page.

### Additional context
<img width="1204" alt="Screenshot 2020-09-29 at 11 17 49" src="https://user-images.githubusercontent.com/10044708/94539482-91f9d380-0245-11eb-9ef7-5a528cb0ad6b.png">

**Comment by bencroker** [comment]
Thanks, disabled recommendations for CP requests in https://github.com/putyourlightson/craft-blitz-recommendations/commit/9bd7ad5ee8c5613ff6c8e554e6857912e7a53b38.
