### ISSUE TITLE
Missing template in recommendations

### ISSUE THREAD

**Issue by SHoogland** [putyourlightson/craft-blitz-recommendations#5]
### Question
How do i track down recommendations like these:
![image](https://user-images.githubusercontent.com/2057831/119635386-ec1e5900-be13-11eb-962e-ee92e35bf999.png)

Or is this a bug maybe?
Could it be the graphql api?
Just checkin if this is something you guys seen before :)

### Additional context
blitz v1.2.0
craft v3.6.12

**Comment by bencroker** [comment]
Is this also happening if you clear all recommendations and visit a page that does _not_ use GraphQL?

**Comment by SHoogland** [comment]
I'm not sure, I haven't been able to pin it down to a specific request, when I'm searching for it, it doesn't happen, but when I return a week later, there are some entries...

**Comment by bencroker** [comment]
Likely being called from GraphQL or another source then. This plugin is intended to help you debug your templates, so as long as they are good the plugin has done its job.
