### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by bengreenbank** [putyourlightson/craft-blitz-recommendations#6]
### Describe the solution you would like
A console command to be created that clears the Blitz recommendations stored in the DB, so that we can run the command on each deploy, to avoid stale recommendations.

### Describe alternatives you have considered
Manually clearing the recommendations in the CMS after each deploy.

**Comment by bencroker** [comment]
Great suggestion! Added in https://github.com/putyourlightson/craft-blitz-recommendations/commit/f3a9a8c8406f6e73fe9f89ddbc137e2480467f23 and released in version 1.3.0.

**Comment by bengreenbank** [comment]
Thanks for the speedy implementation!
