### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by kylecotter** [putyourlightson/craft-blitz-recommendations#9]
### Is your feature request related to a problem? Please describe.
Any plans on upgrading this to Craft 4? This has been a handy utility for double checking template efficiencies.

### Describe the solution you would like
This plugin available for Craft 4.

Thanks!

**Comment by bencroker** [comment]
Yes, I'm working through the free plugins, this one needs more testing though. In the meantime the Elements Panel plugin already works with Craft 4: https://putyourlightson.com/plugins/elements-panel

**Comment by bencroker** [comment]
Just released version 2.0.0 for Craft 4.
